<?php

/**
 * Remove variables from any environment that would have this information
 *
 * Implements hook_uninstall().
 */
function acquia_search_multi_subs_uninstall() {
  variable_del('apachesolr_environments');
  $environments = apachesolr_load_all_environments();
  foreach ($environments as $environment) {
    apachesolr_environment_variable_del($environment['env_id'], 'acquia_search');
    apachesolr_environment_variable_del($environment['env_id'], 'acquia_search_key');
    apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_subscription_corename');
    apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_selector');
    apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_subscription_key');
    apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_subscription_id');
    apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_auto_switch');
  }
}

/**
 *
 * Remove config overrides
 *
 * Implements hook_disable().
 */
function acquia_search_disable() {
  // we want to also remove all config overrides when we disable it to avoid
  // confusion
  acquia_search_multi_subs_uninstall();
}

/**
 * Set auto switch variable to true for all environments
 *
 * Implements hook_install().
 */
function acquia_search_multi_subs_install() {
  $environments = apachesolr_load_all_environments();
  foreach ($environments as $environment) {
    if ($environment['service_class'] == 'AcquiaSearchService') {
      apachesolr_environment_variable_set($environment['env_id'], 'acquia_override_auto_switch', 1);
    }
  }
}
